version: "3.9"

services:
  db:
    container_name: postgres-prod
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=main
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=testpass
    ports:
      - 5050:80
    restart: always
    depends_on:
      - db
    volumes:
      - pgadmin:/root/.pgadmin

  server:
    container_name: server-prod
    ports:
      - 3000:3000
    build: .
    env_file:
      - ./.env.production
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx
    environment:
      DOMAIN: $DOMAIN
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    container_name: certbot
    image: certbot/certbot
    depends_on:
      - nginx
    environment:
      DOMAIN: $DOMAIN
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


volumes:
  pgadmin:
  pgdata:
