version: "3.9"

services:
  db:
    container_name: postgres-prod
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=main
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: server-prod
    ports:
      - 3000:3000
    image: advicedayserver:1.0.0
    env_file:
      - ./.env.production
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - db
  nginx:
    image: nginx
    environment:
      DOMAIN: localhost
    depends_on:
      - server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d


volumes:
  pgdata:
