version: "3.9"

services:
  db:
    container_name: postgres-dev
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=main
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: server-dev
    env_file:
      - ./.env.development
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: Dockerfile-development
    depends_on:
      - db

volumes:
  pgdata:
