version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}
      - run:
          name: "Install dependencies"
          command: "npm i -D"
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Format code"
          command: "npm run format"
      - run:
          name: "Lint code"
          command: "npm run lint"
      - run:
          name: "Lint doc coverage"
          command: "npm run test:doccov"
  deploy:
    docker:
      - image: circleci/node
    resource_class: small
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a7:90:dc:89:26:85:2c:21:3f:03:e0:ca:9c:c1:e4:ee"
      - checkout
      - run:
          name: Add to known hosts
          command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
#      - run:
#          name: Disable host checking
#          command: bash ./disable_host_key_checking.sh
      - run: ls
      - run:
          name: Connect to server
          command: "ssh adviceday@178.154.206.107 'bash -s' < ./circleci/deploy.sh"
      - run:
          name: Check path
          command: pwd
#      - run:
#          name: "Install dependencies"
#          command: "npm i"
#      - run:
#          name: ""

workflows:
  deploy_to_server:
    jobs:
      - lint
      - deploy
