version: 2.1

jobs:
  deploy_docs:
    docker:
      - image: circleci/node
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}
      - run:
          name: "Install dependencies"
          command: "npm i -D"
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build docs
          command: "npm run docgen"
      - run:
          name: Deploy docs
          command: "./node_modules/.bin/surge --project ./documentation --domain adviceday-docs.surge.sh"
  lint:
    docker:
      - image: circleci/node
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}
      - run:
          name: "Install dependencies"
          command: "npm i -D"
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Format code"
          command: "npm run format"
      - run:
          name: "Lint code"
          command: "npm run lint"
      - run:
          name: "Lint doc coverage"
          command: "npm run test:doccov"
  deploy:
    docker:
      - image: circleci/node
    resource_class: small
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:6f:e6:40:ff:58:2d:d3:84:f8:66:0a:2e:2a:ac:db"
      - run:
          name: Add to known hosts
          command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
      - checkout
      - run:
          name: Connect to server and run script
          command: "ssh $SERVER_USER@$SERVER_IP 'bash -s' < .circleci/deploy.sh"
      - run:
          name: Connect to server and run after_deploy script
          command: "ssh $SERVER_USER@$SERVER_IP 'bash -s' < .circleci/after_deploy.sh"
      - run:
          name: Ping server
          command: "npm run health_check"
  after_deploy_checks:
    docker:
      - image: circleci/base
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Pint server
          command: "npm run health_check"
      - run:
          name: Ping docs
          command: "npm run health_check:doc"

workflows:
  deploy:
    jobs:
      - lint
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - lint
      - deploy_docs:
          filters:
            branches:
              only:
                - master
          requires:
            - lint
      - after_deploy_checks:
          requires:
            - deploy
            - deploy_docs
