version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package.json" }}
      - run:
          name: "Install dependencies"
          command: "npm i -D"
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Format code"
          command: "npm run format"
      - run:
          name: "Lint code"
          command: "npm run lint"
      - run:
          name: "Lint doc coverage"
          command: "npm run test:doccov"
  deploy:
    docker:
      - image: circleci/node
    resource_class: small
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ee:33:b6:5b:a7:1c:3a:d6:42:a1:a8:24:0e:6a:b9:39"
      - run:
          name: Add to known hosts
          command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
      - run:
          name: Connect to server and run script
          command: "ssh adviceday@178.154.206.107 'bash -s' < ./.circleci/deploy.sh"

workflows:
  deploy_to_server:
    jobs:
#      - lint
      - deploy
