version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run:
          name: "Install dependencies"
          command: "npm i -D"
      - save_chache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Format code"
          command: "npm run format"
      - run:
          name: "Lint code"
          command: "npm run lint"
      - run:
          name: "Lint doc covarage"
          command: "npm run test:doccov"
#  deploy:
#    docker:
#      - image: cimg/node
#    steps:
#      - checkout
#      - run:
#          name: "Install dependencies"
#          command: "npm i"
#      - run:
#          name: ""

workflows:
  deploy_to_server:
    jobs:
      - lint
